### PR TITLE
Pre-generate default config during container build

### PR DESCRIPTION
**Pull request by dtantsur**
There is no point in generating static configuration in runtime.

Also get rid of hardcoding ignition.conf in favour of using config-dir.
Rename the default configuration so that it always goes first (and thus
can be overridden).

### CODE REVIEW

**Review by iurygregory — APPROVED** [review]

**Comment by dtantsur** [comment]
/approve

huh?

**Comment by fmuyassarov** [comment]
> /approve
> 
> huh?

Prow is on PTO :). It started to show some flakiness and being re-build right now. Sorry for that.

**Pull request merged**
